# Generated by Django 5.1.1 on 2024-09-18 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=100)),
                ('course_link', models.URLField(max_length=500)),
                ('original_price', models.CharField(max_length=50)),
                ('image_link', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
